# testthat loads helper files in alphabetical order, so helper-toy-model.R
# (needed below) would otherwise load *after* this file -- source it
# explicitly rather than relying on load order.
source(testthat::test_path("helper-toy-model.R"), local = TRUE)

# `er_test_data` is a frozen snapshot of `erglm::erglm_data` (see
# `tests/testthat/fixtures/er_test_data.rds` -- regenerated by hand with
# `saveRDS(erglm::erglm_data, "tests/testthat/fixtures/er_test_data.rds",
# version = 2)` if erglm's own `erglm_data` is ever revised), so most of the
# suite doesn't need erglm installed just to get a data frame with the
# right column names/shape.
er_test_data <- readRDS(testthat::test_path("fixtures", "er_test_data.rds"))

# `er_test_mod1`/`er_test_mod2`/`er_test_mod_gaussian` are built via the
# internal, test-only `er_test_toy_model()` (see helper-toy-model.R)
# instead of `erglm::erglm_model()`, so they -- and the many tests that
# just consume them -- don't require erglm to be installed.
er_test_mod1 <- er_test_toy_model(ae1 ~ aucss, er_test_data, family = binomial())
er_test_mod2 <- er_test_toy_model(ae1 ~ aucss + sex, er_test_data, family = binomial())
# continuous-response fixture, used by the Stage 0 (and later) tests for
# response-type detection/handling
er_test_mod_gaussian <- er_test_toy_model(biomarker_change ~ aucss, er_test_data, family = gaussian())

if (requireNamespace("erglm", quietly = TRUE)) {
  # count-response fixture. `er_test_toy_model()` deliberately doesn't
  # support Poisson (see helper-toy-model.R), so this one stays erglm-backed
  # and gated. Count responses auto-detect as "continuous" and are routed
  # through the same mean + t-interval path (a documented approximation,
  # not an exact Poisson interval).
  er_test_mod_poisson <- erglm::erglm_model(ae_count ~ aucss, er_test_data, family = poisson())
}

# test-only fixture with no `er_predict()` method, used to exercise the
# `er_summary()` contract's `coefficients`/`glance` fields (see
# `?er_model_interface`) without depending on erglm implementing them --
# `.layer_summary()` never calls `er_predict()`, so this is enough for
# `er_plot_add_summary(model = ...)`, but not for `er_plot_add_model()`.
er_summary.er_test_fake_summary_model <- function(model, ...) {
  list(
    p_value = NULL, # e.g. a multi-parameter model with no single privileged term
    coefficients = tibble::tibble(
      term = c("(Intercept)", "aucss"),
      estimate = c(0.1, 0.02),
      p_value = c(0.5, 0.02)
    ),
    glance = tibble::tibble(n = 100L, aic = 123.4, bic = 130.1, r_squared = 0.42)
  )
}
# a second fixture with a partially-populated `glance` (only `aic`; `bic`/
# `r_squared` absent, `n` present but `NA`) -- exercises
# `er_style_summary_gof()`'s "show only what's present and non-NA" branch
er_summary.er_test_partial_gof_model <- function(model, ...) {
  list(glance = tibble::tibble(n = NA_integer_, aic = 88.8))
}
# `er_summary()` is called from inside erplots' own internals
# (`.layer_summary()`), several frames away from this test file, so plain
# lexical scoping won't find an informally-defined method here -- register
# it explicitly, the same runtime pattern erglm itself uses (see AGENTS.md).
registerS3method("er_summary", "er_test_fake_summary_model", er_summary.er_test_fake_summary_model)
registerS3method("er_summary", "er_test_partial_gof_model", er_summary.er_test_partial_gof_model)

# test-only fixture used to exercise `er_vpc_add_simulated(model = ...)`
# without depending on erglm/emaxnls implementing the `sim_resp` extension
# to `er_simulate()` -- see `?er_model_interface`. `prob` is the (constant,
# covariate-independent) response probability used to draw simulated
# binary responses; `fit_resp` is included alongside `sim_resp` in the
# returned data frame to mirror the real contract (a method can supply
# both from one call).
er_simulate.er_test_fake_vpc_model <- function(model, newdata, nsim = 100, seed = NULL, ...) {
  reps <- vector("list", nsim)
  withr::with_seed(seed %||% 1, {
    for (ii in seq_len(nsim)) {
      row <- newdata
      row$sim_id <- ii
      row$fit_resp <- model$prob
      row$sim_resp <- stats::rbinom(nrow(newdata), size = 1, prob = model$prob)
      reps[[ii]] <- row
    }
  })
  dplyr::bind_rows(reps)
}
# a second fixture with only `fit_resp` (no `sim_resp`), used to exercise
# `er_vpc_add_simulated(model = ...)`'s "predictive simulation not
# available" error path -- this is the shape every `er_simulate()` method had before
# `sim_resp` was added to the contract (e.g. still true of erglm/emaxnls
# at the time this fixture was written).
er_simulate.er_test_fake_spaghetti_only_model <- function(model, newdata, nsim = 100, seed = NULL, ...) {
  reps <- vector("list", nsim)
  withr::with_seed(seed %||% 1, {
    for (ii in seq_len(nsim)) {
      row <- newdata
      row$sim_id <- ii
      row$fit_resp <- model$prob
      reps[[ii]] <- row
    }
  })
  dplyr::bind_rows(reps)
}
registerS3method("er_simulate", "er_test_fake_vpc_model", er_simulate.er_test_fake_vpc_model)
registerS3method("er_simulate", "er_test_fake_spaghetti_only_model", er_simulate.er_test_fake_spaghetti_only_model)
